---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - git
    - build-essential
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - autojump
    - tree
  become: true

- name: Create home bin dir
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: "directory"
    mode: 0750
